name: push_main_doc

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/check_available
  push-main-doc:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "14.x"
      - uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.LSOPEN_SSH_PRIV_KEY }}
      - name: "[Main Doc] checkout"
        run: cd ~ && git clone git@github.com:LISTENAI/LSOpenWeb.git lsopenweb
      - name: "[Main Doc] submodule sync"
        run: cd ~/lsopenweb && git submodule update --init --recursive
      - name: "[Main Doc] Find submodule path"
        id: find-submodule
        run: |
          submodule_path=$(node .github/workflows/find_submodule_path.js ~/lsopenweb/ $GITHUB_REPOSITORY)
          echo ::set-output name=submodule_path::"$submodule_path"
      - name: "[Sub Doc] Checkout doc to current commit"
        run: |
          cd ~/lsopenweb/${{ steps.find-submodule.outputs.submodule_path }}
          git fetch origin
          git checkout "$GITHUB_SHA"
      - name: "[Main Doc] Commit"
        run: |
          cd ~/lsopenweb/
          git add ${{ steps.find-submodule.outputs.submodule_path }}
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit -m "actions: Update $GITHUB_REPOSITORY to $GITHUB_SHA"
      - name: "[Main Doc] Push changes"
        run: |
          cd ~/lsopenweb/
          git push origin master
